# Generated by Django 5.1.15 on 2026-08-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_role', models.CharField(choices=[('ALL', 'All Users'), ('STUDENT', 'Students Only'), ('FACULTY', 'Faculty Only'), ('STAFF', 'Staff Only')], default='ALL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=15)),
                ('is_pinned', models.BooleanField(default=False)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
