version: '3.8'

services:
  backend:
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --threads 2 config.wsgi:application
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  db:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
